### PR TITLE
refactor: fix transformer versions

### PR DESCRIPTION
**Pull request by JoanFM**
Transformers 4.0.0 broke something

### CODE REVIEW

**Comment by cristianmtr** [comment]
Some requirements conflicts

**Review by cristianmtr — CHANGES_REQUESTED** [review]
Rebase

**Comment by JoanFM** [comment]
> Rebase

Done! Thx!

**Review by cristianmtr — APPROVED** [review]
What's the status on this?

**Comment by JoanFM** [comment]
This should be closed, because our torch encoder seems to work with 4.0.1

**Pull request closed without merging**
