### PR TITLE
fix[audio]: adapt segmenter for changes

### PR DESCRIPTION
**Pull request by Yongxuanzhang**
Issue: https://github.com/jina-ai/examples/issues/429
Reason: https://github.com/jina-ai/jina/pull/2141 
Another solution: https://github.com/jina-ai/jina/pull/2172
Ref: 
https://github.com/jina-ai/jina/issues/2176
https://github.com/jina-ai/jina/pull/2178

Need to wait for the changes of batching are done.

### CODE REVIEW

**Comment by Yongxuanzhang** [comment]
Simple adding @single for segment won't fix this audio example, what should be the correct way to fix it instead of the code that I write now?
@JoanFM @nan-wang

**Comment by JoanFM** [comment]
It is possible that it will break, I am coming with a fix that should make the addition of single good enough

**Comment by Yongxuanzhang** [comment]
> It is possible that it will break, I am coming with a fix that should make the addition of single good enough

Cool, so I will wait for your fix? After that @single should be able to work?

**Review by nan-wang — APPROVED** [review]
LGTM👍

**Pull request merged**
