### PR TITLE
docs(tumblr_gifs): corrected the syntax in the example documentation

### PR DESCRIPTION
**Pull request by Shubhamsaboo**

### CODE REVIEW

**Review by nan-wang — APPROVED** [review]
LGTM👍

**Comment by nan-wang** [comment]
Bad commit message, please refer to:
- [Commit Message Guideline for the First Time Contributor](https://github.com/jina-ai/jina/issues/553)
- [Contributing Guideline](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md)
#553 :bookmark: Commit Message Guideline for the First Time Contributor

**Review by nan-wang — CHANGES_REQUESTED** [review]
Bad commit message, please refer to:
- [Commit Message Guideline for the First Time Contributor](https://github.com/jina-ai/jina/issues/553)
- [Contributing Guideline](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md)

**Review by Yongxuanzhang — COMMENTED** [review]
shall we merge/close this one? Since Tumblr is not kept in 2.0. @nan-wang

**Pull request closed without merging**
