### PR TITLE
Draft: Template scrap news example

### PR DESCRIPTION
**Pull request by carlosb1**
First iteration for example that it scrap news and save in  jina as a retrieve search engine.

### CODE REVIEW

**Comment by JoanFM** [comment]
It is a little weird this example, can you clarify the intention of it? I see there are like 2 ways to index? I would prefer to focus it in one single problem (maybe this Article link can be interesting)

**Comment by alexcg1** [comment]
Thanks for your example @carlosb1!

Since we are restructuring our examples repo now, do you think it would be better if @carlosb1 hosted this in his own repo @JoanFM ? I'll add a section to our readme for community examples and link it from there

**Comment by carlosb1** [comment]
> Thanks for your example @carlosb1!
> 
> Since we are restructuring our examples repo now, do you think it would be better if @carlosb1 hosted this in their own repo @JoanFM ? I'll add a section to our readme for community examples and link it from there

I did some modifications (I removed not used functions). However, if you prefer move my minimal example, ok for me.

**Comment by JoanFM** [comment]
> > Thanks for your example @carlosb1!
> > Since we are restructuring our examples repo now, do you think it would be better if @carlosb1 hosted this in their own repo @JoanFM ? I'll add a section to our readme for community examples and link it from there
> 
> I did some modifications (I removed unused functions). However, if you prefer move my minimal example, ok for me.

Yes we should move it and link it in our repo.

As per the content, is it just indexing the title of the articles?

**Comment by carlosb1** [comment]
> > > Thanks for your example @carlosb1!
> > > Since we are restructuring our examples repo now, do you think it would be better if @carlosb1 hosted this in their own repo @JoanFM ? I'll add a section to our readme for community examples and link it from there
> > 
> > 
> > I did some modifications (I removed unused functions). However, if you prefer move my minimal example, ok for me.
> 
> Yes we should move it and link it in our repo.
> 
> As per the content, is it just indexing the title of the articles?

yes.... my idea is the creation of an incremental example while I understand better the library.

**Comment by alexcg1** [comment]
Hey @carlosb1, feel free to make PR to our examples repo README when you're done. Just add your example under [community examples](https://github.com/jina-ai/examples#community-examples)

**Pull request closed without merging**
