### PR TITLE
fix: added uri conversion for jinabox

### PR DESCRIPTION
**Pull request by bhavsarpratik**
For multimodal in jinabox

### CODE REVIEW

**Review by JoanFM — COMMENTED** [review]
Isn't there a `Buffer2Uri` before the `KVIndexer`?

**Comment by bhavsarpratik** [comment]
In object-search there is one `Buffer2Uri` in doc.yml's index side which we also have. Although we need to worry only searchrequest side

**Comment by JoanFM** [comment]
> In object-search there is one `Buffer2Uri` in doc.yml's index side which we also have. Although we need to worry only searchrequest side

So right now we are using some uri parsing at the client side to show the results?

**Comment by bhavsarpratik** [comment]
Yes we have conversion in our `app.py`

**Comment by JoanFM** [comment]
> Yes we have conversion in our `app.py`

Ok now I understand!

**Pull request closed without merging**
