### PR TITLE
test: run southpark distributed on jina master

### PR DESCRIPTION
**Pull request by maximilianwerk**
Missing thing: run if on jinad master. This needs the completion of code movement from jinad to jina.

### CODE REVIEW

**Comment by JoanFM** [comment]
Is it run now in jina master CI? yes I believe right?

**Comment by JoanFM** [comment]
We can do this change for any `test` (and have specific requirements per `test`)? because it may not be happening right now?

**Comment by maximilianwerk** [comment]
It may make sense for any test. Currently I only did it for the one isolated in a docker image.

**Comment by JoanFM** [comment]
LGTM!

**Review by theUnkownName — APPROVED** [review]
Looks good!

**Pull request merged**
