### PR TITLE
Fixing a few typos

### PR DESCRIPTION
**Pull request by khituras**
Just fixing a few types and proposing slight reformulations.

### CODE REVIEW

**Comment by alexcg1** [comment]
Hey khituras - thanks for your contribution. I'm working on overhauling our tutorials at the moment and haven't got round to this one yet, so thanks for the feedback! Your changes look good to me but I'll check with the rest of the team.

Aaaaand, you're based in Jena and submitting an issue to Jina? That's an interesting coincidence :)

**Comment by khituras** [comment]
I will continue to do your tutorials today. I assume further contributions - if I stumble about them - would be welcome?

And yes, it's true, I'm from Jena :-) Jena-Jina is a nice coincidence. Really confusing, however, is the ontology parsing API `Jena` ;-)

**Comment by alexcg1** [comment]
Contributions are always welcome! Feel free to join our Slack and especially the documentation channel - it'd be good to bounce around my ideas about an overhaul!

**Comment by khituras** [comment]
Alright! I joined your Slack weeks ago - but I don't see a documentation channel. How could I join?

**Comment by alexcg1** [comment]
Added you just now!

**Comment by alexcg1** [comment]
I'll be offlining soon though. I'm in NZ and it's getting late here, so might not get a timely reply if you post there right away ;)

**Pull request merged**
