### PR TITLE
[W.I.P] [DO NOT MERGE]fix(examples): migrate webqa to jina master version

### PR DESCRIPTION
**Pull request by xiongma**

### CODE REVIEW

**Comment by policeme** [comment]
this pr related to jina master version, **don't merge**
this pr should change 2 file in jina master
1. `BaseRecursiveDriver`
```
if 'chunks' in self.traverse_fields:
        _traverse(docs, 'chunks')
if 'matches' in self.traverse_fields:
        for d in docs:
            _traverse(d.matches, 'matches')
```
to
```
if 'chunks' in self.traverse_fields:
       _traverse(docs, 'chunks')
```
2. `KVSearchDriver`
```
def _apply_all(self, docs: Iterable['jina_pb2.Document'], *args, **kwargs):
    miss_idx = []  #: missed hit results, some search may not end with results. especially in shards
    for idx, retrieved_doc in enumerate(docs):
        r = self.exec_fn(retrieved_doc.id)
        if r:
            retrieved_doc.MergeFrom(r)
        else:
            miss_idx.append(idx)

    # delete non-existed matches in reverse
    for j in reversed(miss_idx):
        del docs[j]
```
to 
```
def _apply(self, doc: 'jina_pb2.Document', *args, **kwargs):
    miss_idx = []  #: missed hit results, some search may not end with results. especially in shards
    for idx, retrieved_doc in enumerate(doc.matches):
        r = self.exec_fn(retrieved_doc.id)
        if r:
            retrieved_doc.MergeFrom(r)
        else:
            miss_idx.append(idx)

# delete non-existed matches in reverse
    for j in reversed(miss_idx):
        del doc.matches[j]
```

**Comment by JoanFM** [comment]
> this pr related to jina master version, **don't merge**
> this pr should change 2 file in jina master
> 
> 1. `BaseRecursiveDriver`
> 
> ```
> if 'chunks' in self.traverse_fields:
>         _traverse(docs, 'chunks')
> if 'matches' in self.traverse_fields:
>         for d in docs:
>             _traverse(d.matches, 'matches')
> ```
> 
> to
> 
> ```
> if 'chunks' in self.traverse_fields:
>        _traverse(docs, 'chunks')
> ```
> 
> 1. `KVSearchDriver`
> 
> ```
> def _apply_all(self, docs: Iterable['jina_pb2.Document'], *args, **kwargs):
>     miss_idx = []  #: missed hit results, some search may not end with results. especially in shards
>     for idx, retrieved_doc in enumerate(docs):
>         r = self.exec_fn(retrieved_doc.id)
>         if r:
>             retrieved_doc.MergeFrom(r)
>         else:
>             miss_idx.append(idx)
> 
>     # delete non-existed matches in reverse
>     for j in reversed(miss_idx):
>         del docs[j]
> ```
> 
> to
> 
> ```
> def _apply(self, doc: 'jina_pb2.Document', *args, **kwargs):
>     miss_idx = []  #: missed hit results, some search may not end with results. especially in shards
>     for idx, retrieved_doc in enumerate(doc.matches):
>         r = self.exec_fn(retrieved_doc.id)
>         if r:
>             retrieved_doc.MergeFrom(r)
>         else:
>             miss_idx.append(idx)
> 
> # delete non-existed matches in reverse
>     for j in reversed(miss_idx):
>         del doc.matches[j]
> ```

In the change you propose, don't we assume that `KVSearchDriver` is called with `docs` that do have `matches`? Isn't it better to keep the caller to `apply_all` responsible for looping on the `matches`? After all, `SearchDriver` should only be responsible to ask the executor `search` what he is given as input right?

**Comment by policeme** [comment]
when we finished useing vector to search similarity chunk,  the matches just in second level. and then we start geting their doc id
but when we are getting their doc id, in this kind of codes
```
if 'matches' in self.traverse_fields:
        for d in docs:
            _traverse(d.matches, 'matches')
```
it didn't has matches in first level, so it wouldn't dig into `_traverse`

**Comment by JoanFM** [comment]
Is the problem you are facing at `docIndexer` level? because it could be related to https://github.com/jina-ai/jina/issues/763

**Comment by policeme** [comment]
my explanation was wrong, let me found a better way to use `apply_all`

**Comment by policeme** [comment]
I think this would be the best change
```
    def _apply_all(self, docs: Iterable['jina_pb2.Document'], *args, **kwargs):
        for doc in docs:
            miss_idx = []  #: missed hit results, some search may not end with results. especially in shards
            for idx, match in enumerate(doc.matches):
                r = self.exec_fn(match.id)
                if r:
                    match.MergeFrom(r)
                else:
                    miss_idx.append(idx)

        # delete non-existed matches in reverse
            for j in reversed(miss_idx):
                del doc.matches[j]
```

**Comment by JoanFM** [comment]
> I think this would be the best change
> 
> ```
> def _apply_all(self, docs: Iterable['jina_pb2.Document'], *args, **kwargs):
>     for doc in docs:
>         miss_idx = []  #: missed hit results, some search may not end with results. especially in shards
>         for idx, match in enumerate(doc.matches):
>             r = self.exec_fn(match.id)
>             if r:
>                 match.MergeFrom(r)
>             else:
>                 miss_idx.append(idx)
> 
>     # delete non-existed matches in reverse
>         for j in reversed(miss_idx):
>             del doc.matches[j]
> ```

What if we want to use `KVSearchDriver` before `VectorSearchDriver`. I know it is not the most common pattern, but I think we are adding a dependency there that we avoid by having it loop through `docs`

**Comment by nan-wang** [comment]
This is related to this PR. https://github.com/jina-ai/jina/pull/765

**Pull request closed without merging**
