### PR TITLE
remove docker image from index flow

### PR DESCRIPTION
**Pull request by theUnkownName**
No need to have the faiss docker image in index flow time

### CODE REVIEW

**Comment by JoanFM** [comment]
Please @theUnkownName solve the conflicts before being able to merge this chanes

**Comment by nan-wang** [comment]
This will require the installation of `faiss` which is overcomplicated for running an example.

**Comment by JoanFM** [comment]
Notice that is just at index time when just NumpyIndexer is used

**Comment by nan-wang** [comment]
I see. Then it is fine.

**Comment by JoanFM** [comment]
It is now more `explicit` the fact that we can switch `indexer` at `query time`

**Pull request merged**
