### PR TITLE
update cross modal search to 1.2

### PR DESCRIPTION
**Pull request by nan-wang**
update cross modal search to 1.2

### CODE REVIEW

**Comment by nan-wang** [comment]
The `image_encoder` is broken with the following error message,
```output
RuntimeError: Given groups=1, weight of size [768, 3, 32, 32], expected input[1, 224, 224, 3] to have 3 channels, but got 224 channels instead
```

**Review by bwanglzu — APPROVED** [review]
LGTM!

**Comment by bwanglzu** [comment]
testing with @davidbp seems it's not working

**Comment by bwanglzu** [comment]
jina version is not identical to the encoder version, so query hangs.

**Pull request merged**
