### PR TITLE
fix: update object-search requirements

### PR DESCRIPTION
**Pull request by Yongxuanzhang**
Since Minranker is removed, 'search original' cannot work.
And in Jina==1.0.4 when do indexing, `AttributeError: meta_info is not recognized` occurs.

- [x] Specify the working environments for object-search.
- [x] fix ranker
- [x] fix segmenter in hub -> https://github.com/jina-ai/jina-hub/pull/4688
- [x] add into ci

### CODE REVIEW

**Review by JoanFM — CHANGES_REQUESTED** [review]
This shouldn't be merged until the example itself is updated to work with the specified version

**Comment by Yongxuanzhang** [comment]
> This shouldn't be merged until the example itself is updated to work with the specified version

Sure. I will just keep it as a temporary record of a working environment. And try to update it to the latest version.

**Review by bwanglzu — APPROVED** [review]
LGTM! while seems `tumblr search` CI had an error.

**Comment by Yongxuanzhang** [comment]
> LGTM! while seems `tumblr search` CI had an error.

Yes, that's another issue non-related to this one. ;)

**Comment by nan-wang** [comment]
> > LGTM! while seems `tumblr search` CI had an error.
> 
> Yes, that's another issue non-related to this one. ;)

I've fixed the unittests

**Comment by Yongxuanzhang** [comment]
> > > LGTM! while seems `tumblr search` CI had an error.
> > 
> > 
> > Yes, that's another issue non-related to this one. ;)
> 
> I've fixed the unittests

[Tumblr](https://github.com/jina-ai/examples/pull/407/checks?check_run_id=2013753507) is failing and the object-search test could pass.

**Pull request merged**
