### PR TITLE
refactor: define encoder in yaml

### PR DESCRIPTION
**Pull request by slettner**
Solves https://github.com/jina-ai/examples/issues/480

### CODE REVIEW

**Review by Yongxuanzhang — APPROVED** [review]
Thanks!

**Review by nan-wang — DISMISSED** [review]
LGTM👍

**Comment by nan-wang** [comment]
@slettner Please fix the the conflicts.

**Review by Yongxuanzhang — APPROVED** [review]
LGTM! 👍

**Pull request merged**
