### PR TITLE
Migrate face db search example to Jina 0.4.1

### PR DESCRIPTION
**Pull request by bwanglzu**
This PR was aligned with issue #116 , migrate face db search example for Jina 0.4.1 release, includes:

1. Code migration based on [migration guide](https://github.com/jina-ai/jina/issues/702).
2. Minor refactoring to replace `SegmentDriver` with `CraftDriver` in `yaml/craft_load`, to make the example work.
3. Some minor changes on Readme.

Apart from this, while debugging `make_html.py`, `match.meta_info` gives me an empty buffer, might need to update `jina`. Please see attached image blow.

image

@JoanFM Spent a lot of time helping me walking through this process, special thanks to him!

### CODE REVIEW

**Comment by JoanFM** [comment]
What is the difference between make_html and app.py when it comes to search and getting results?

**Comment by nan-wang** [comment]
> What is the difference between make_html and app.py when it comes to search and getting results?

Both are motivated to visualize the query results. I'd suggest to unify to `app.py`, which uses [jinabox](https://jina.ai/jinabox.js/) to show the results. `make_html.py` is a stand-alone solution inherited from `hello-world`.

**Comment by kaushikb11** [comment]
@bwanglzu While running `make_html.py`, `match.meta_info` is still giving an empty buffer. Was it fixed?

**Comment by bwanglzu** [comment]
@kaushikb11 This PR is about to migrate example to a new Jina version, I'll create a new issue and investigate this error :)

**Comment by JoanFM** [comment]
@kaushikb11 @bwanglzu. This issue is most likely related to one being handled in the PR #132

**Comment by kaushikb11** [comment]
Noted! Thanks for the update. Will look into it as well.

**Pull request merged**
